### ISSUE TITLE
Swimming not working for Pavlov 2020.3.5

### ISSUE THREAD

**Issue by DKingAlpha** [Yoshey/AdvancedMovement#2]
In AMM Example Map I can swim in Water actor. And I can play a AMM_FPSPawn swimming in a new default Water actor in my own map.

But in actual pavlov game, offline - GUN mode, the swim system is not working.

Besides, I have problem to jump for my first life in GUN mode. I can't jump nor see the AMM setting icon until respawn.

**Comment by DKingAlpha** [comment]
So I read your previous reply in discord, should I expect swim not to work in offline mode?

**Comment by Yoshey** [comment]
You shouldn't expect any AMM logic to work properly in offline mode, as I did not develope AMM with offline mode in mind. In general, custom logic can behave unexpectedly in offline mode, since there, the client is the server, while AMM is developed expecting the client and server to be seperate entitites.
Considering that swimming works mostly client-sided, it could be possible to be made functional in offline mode. However, that is not something I would implement support for myself, since I wouldn't see much value in that.

About the jumping - I'm not aware of it, so I'll write it down as a bug. But real life is keeping me really busy currently, so I can't tell you an estimate of when I'll get around to fix it or if I'll get to it anytime soon.

**Comment by DKingAlpha** [comment]
Thanks for your response. These problems only occur in offline mode. It's not a big problem for me now since the mod is for online, but I guess it's better to have that note in README.

**Comment by DKingAlpha** [comment]
If I can figure it out I will try to fix it and send a PR

**Comment by Yoshey** [comment]
good point to include it in the readme, will do.
If you figured it out, I'll merge the PR. It must probably be something about the initialization - I believe some default gamemodes don't spawn all proxies in the gamelogic on first spawn, so I would first check if the AMM PlayerProxy, AMM Playerinfo, AMM GlobalInfo and AMM HandProxies are all valid on first spawn in GUN mode.
If it isn't that, perhaps the proxy gets stuck during initialization. There are a bunch of loops that only proceed once the required variables are found - so if one of them never returns valid, it will never proceed to reach the hand initialization as it wouldn't be able to ever leave the loop. The question is at what point does the jump blueprint fail, and if it is already failing to receive the playerinput for jump in the first place or not, and if it is being received, then we should be able to identify which part of the jump code fails with some debugging.
